# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

install!  'cocoapods',
          :deterministic_uuids                => false,
          :generate_multiple_pod_projects     => false

###################################################################################################################################

def github_pod(pod_name, file = pod_name, type = 'remote', branch = 'master', modular_headers = true)
  case type
    when 'local'
      pod pod_name, :path => "../../../../MINIWING-PODs/#{file}"           , :inhibit_warnings => false, :modular_headers => modular_headers
    when 'remote'
      pod pod_name, :git  => "git@github.com:miniwing/#{file}.git", :branch => "#{branch}"    ,     :modular_headers => modular_headers
    else
  end
end

def miniwing_pod(pod_name, file = pod_name, type = 'remote', branch = 'master', modular_headers = true)
  case type
    when 'local'
      pod pod_name, :path => "../../../../MINIWING-PODs/#{file}"           , :inhibit_warnings => false, :modular_headers => modular_headers
    when 'remote'
      pod pod_name, :git  => "git@github.com:miniwing/MINIWING-PODs.git", :branch => "#{branch}"    , :modular_headers => modular_headers
    else
  end
end

###################################################################################################################################

workspace 'TeamTalk'

project 'TeamTalk.xcodeproj'

#use_frameworks!
use_modular_headers!
inhibit_all_warnings!

platform:ios, '10.0'

target 'TeamTalk' do

pod 'Reveal-SDK'              , '~> 24'   , :configurations => ['Debug']

pod 'FMDB'                    , '~> 2.3'
pod 'SDWebImage'              , '~> 3.6'
pod 'AFNetworking'            , '~> 2.3.0'
pod 'DACircularProgress'      , '~> 2.2.0'
pod 'MBProgressHUD'           , '~> 0.8'
pod 'PSTCollectionView'       , :git => "git@github.com:miniwing/PSTCollectionView.git" , :branch => 'develop'
pod 'HPGrowingTextView'       , '~> 1.1'
pod 'ProtocolBuffers'         , '~> 1.9.11'
pod 'SCLAlertView-Objective-C', '~> 0.7.3'
pod 'MWPhotoBrowser'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'SVWebViewController'
pod 'XHImageViewer'
pod 'ZXingObjC'
#pod 'YYKit'                   , :git => "git@github.com:miniwing/YYKit.git"             , :branch => 'develop'

pod 'TZImagePickerController'
pod 'APAddressBook'
pod 'OHAlertView'
pod 'RegexKitLite'
pod 'SVProgressHUD'           , '~> 2.2.5'
pod 'LCActionSheet'           , '~> 1.2.1'
pod 'BaiduMapKit'             , '~> 2.10.0'
pod 'SSKeychain'

#pod 'SDAutoLayout'

github_pod('YYKit', file = 'YYKit', type = 'remote', branch = 'develop', modular_headers = true)
github_pod('FoundationExtension', file = 'FoundationExtension', type = 'remote', branch = 'develop', modular_headers = true)
github_pod('UIKitExtension', file = 'FoundationExtension', type = 'remote', branch = 'develop', modular_headers = true)


miniwing_pod('IDEAColor', file = 'IDEAColor', type = 'local', branch = 'develop', modular_headers = true)
miniwing_pod('IDEANightVersion', file = 'IDEANightVersion', type = 'local', branch = 'develop', modular_headers = true)


pod 'IDEAKit'                 , :path => 'TeamTalk-Pods/IDEAKit'
pod 'IDEAUIKit'               , :path => 'TeamTalk-Pods/IDEAUIKit'
pod 'IDEAUIVendor'            , :path => 'TeamTalk-Pods/IDEAUIVendor'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#    puts "===================>target name #{target.name}"
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET']       = '10.10'
      config.build_settings['TVOS_DEPLOYMENT_TARGET']         = '10.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']     = '10.0'
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET']      = '4.3'
      
      
      if target.name == 'IDEAKit'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                                                                   '$(inherited)',
                                                                   'APP_SCHEME=\@\"TeamTalk://\"',
                                                                   'APP_BUNDLE_IDENTIFIER=\@\"com.idea.TeamTalk\"',
                                                                   'APP_BUNDLE_IDENTIFIER_GROUP=\@\"group.com.idea.TeamTalk\"',
                                                                   'APP_BUNDLE_IDENTIFIER_WIDGET=\@\"com.idea.TeamTalk.Widget\"',
                                                                   'APP_ID=1568321747',
                                                                   'FY_TRANSITION=0',
                                                                   'NS_EVIL_TRANSFORM=0'
                                                                   ]
      end

      end
  end
end
