
workspace 'TeamTalk'

project 'TeamTalk.xcodeproj'

#use_frameworks!
use_modular_headers!
inhibit_all_warnings!

platform:ios, '10.0'

target 'TeamTalk' do

pod 'Reveal-SDK' , '~> 24' , :configurations => ['Debug']

pod 'FMDB'                    , '~> 2.3'
pod 'SDWebImage'              , '~> 3.6'
pod 'AFNetworking'            , '~> 2.3.0'
pod 'DACircularProgress'      , '~> 2.2.0'
pod 'MBProgressHUD'           , '~> 0.8'
pod 'PSTCollectionView'       #, '~> 1.2.1'
pod 'HPGrowingTextView'       , '~> 1.1'
pod 'ProtocolBuffers'         , '~> 1.9.4'
pod 'SCLAlertView-Objective-C', '~> 0.7.3'
pod 'MWPhotoBrowser'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'SVWebViewController'
pod 'XHImageViewer'
pod 'ZXingObjC'
pod 'YYKit'                   , :git => "git@github.com:miniwing/YYKit.git" , :branch => 'develop'
pod 'TZImagePickerController'
pod 'APAddressBook'
pod 'OHAlertView'
pod 'RegexKitLite'
pod 'SVProgressHUD'           , '~> 2.2.5'
pod 'LCActionSheet'           , '~> 1.2.1'
pod 'BaiduMapKit'             , '~> 2.10.0'
pod 'SSKeychain'

#pod 'SDAutoLayout'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#    puts "===================>target name #{target.name}"
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET']       = '10.10'
      config.build_settings['TVOS_DEPLOYMENT_TARGET']         = '10.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']     = '10.0'
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET']      = '4.3'
      end
  end
end
