// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class ContactSessionInfo;
@class ContactSessionInfoBuilder;
@class DepartInfo;
@class DepartInfoBuilder;
@class GroupInfo;
@class GroupInfoBuilder;
@class GroupVersionInfo;
@class GroupVersionInfoBuilder;
@class IMRegistReq;
@class IMRegistReqBuilder;
@class IMRegistRes;
@class IMRegistResBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class MsgInfo;
@class MsgInfoBuilder;
@class OfflineFileInfo;
@class OfflineFileInfoBuilder;
@class PushResult;
@class PushResultBuilder;
@class PushShieldStatus;
@class PushShieldStatusBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
@class ShieldStatus;
@class ShieldStatusBuilder;
@class UnreadInfo;
@class UnreadInfoBuilder;
@class UserInfo;
@class UserInfoBuilder;
@class UserStat;
@class UserStatBuilder;
@class UserTokenInfo;
@class UserTokenInfoBuilder;


typedef NS_ENUM(SInt32, RegistResult) {
  RegistResultRegistResultNoError = 0,
  RegistResultRegistResultErrorGeneric = 1,
  RegistResultRegistResultErrorAlreadyExist = 2,
  RegistResultRegistResultErrorNoDbServer = 3,
  RegistResultRegistResultErrorNoLoginServer = 4,
  RegistResultRegistResultErrorNoRouteServer = 5,
  RegistResultRegistResultErrorNoMsgServer = 6,
  RegistResultRegistResultErrorDbValidateFailed = 7,
  RegistResultRegistResultErrorVersionTooOld = 8,
};

BOOL RegistResultIsValidValue(RegistResult value);
NSString *NSStringFromRegistResult(RegistResult value);


@interface ImregistRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define IMRegistReq_user_name @"userName"
#define IMRegistReq_password @"password"
#define IMRegistReq_client_type @"clientType"
#define IMRegistReq_client_version @"clientVersion"
#define IMRegistReq_attach_data @"attachData"
@interface IMRegistReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  BOOL hasClientVersion_:1;
  BOOL hasAttachData_:1;
  BOOL hasClientType_:1;
  NSString* userName;
  NSString* password;
  NSString* clientVersion;
  NSData* attachData;
  ClientType clientType;
}
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasClientType;
- (BOOL) hasClientVersion;
- (BOOL) hasAttachData;
@property (readonly, strong) NSString* userName;
@property (readonly, strong) NSString* password;
@property (readonly) ClientType clientType;
@property (readonly, strong) NSString* clientVersion;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRegistReqBuilder*) builder;
+ (IMRegistReqBuilder*) builder;
+ (IMRegistReqBuilder*) builderWithPrototype:(IMRegistReq*) prototype;
- (IMRegistReqBuilder*) toBuilder;

+ (IMRegistReq*) parseFromData:(NSData*) data;
+ (IMRegistReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRegistReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMRegistReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRegistReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRegistReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRegistReqBuilder : PBGeneratedMessageBuilder {
@private
  IMRegistReq* resultImregistReq;
}

- (IMRegistReq*) defaultInstance;

- (IMRegistReqBuilder*) clear;
- (IMRegistReqBuilder*) clone;

- (IMRegistReq*) build;
- (IMRegistReq*) buildPartial;

- (IMRegistReqBuilder*) mergeFrom:(IMRegistReq*) other;
- (IMRegistReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRegistReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (IMRegistReqBuilder*) setUserName:(NSString*) value;
- (IMRegistReqBuilder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (IMRegistReqBuilder*) setPassword:(NSString*) value;
- (IMRegistReqBuilder*) clearPassword;

- (BOOL) hasClientType;
- (ClientType) clientType;
- (IMRegistReqBuilder*) setClientType:(ClientType) value;
- (IMRegistReqBuilder*) clearClientType;

- (BOOL) hasClientVersion;
- (NSString*) clientVersion;
- (IMRegistReqBuilder*) setClientVersion:(NSString*) value;
- (IMRegistReqBuilder*) clearClientVersion;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMRegistReqBuilder*) setAttachData:(NSData*) value;
- (IMRegistReqBuilder*) clearAttachData;
@end

#define IMRegistRes_server_time @"serverTime"
#define IMRegistRes_result_code @"resultCode"
#define IMRegistRes_result_string @"resultString"
#define IMRegistRes_user_info @"userInfo"
#define IMRegistRes_attach_data @"attachData"
@interface IMRegistRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResultString_:1;
  BOOL hasUserInfo_:1;
  BOOL hasAttachData_:1;
  BOOL hasServerTime_:1;
  BOOL hasResultCode_:1;
  NSString* resultString;
  UserInfo* userInfo;
  NSData* attachData;
  UInt32 serverTime;
  RegistResult resultCode;
}
- (BOOL) hasServerTime;
- (BOOL) hasResultCode;
- (BOOL) hasResultString;
- (BOOL) hasUserInfo;
- (BOOL) hasAttachData;
@property (readonly) UInt32 serverTime;
@property (readonly) RegistResult resultCode;
@property (readonly, strong) NSString* resultString;
@property (readonly, strong) UserInfo* userInfo;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRegistResBuilder*) builder;
+ (IMRegistResBuilder*) builder;
+ (IMRegistResBuilder*) builderWithPrototype:(IMRegistRes*) prototype;
- (IMRegistResBuilder*) toBuilder;

+ (IMRegistRes*) parseFromData:(NSData*) data;
+ (IMRegistRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRegistRes*) parseFromInputStream:(NSInputStream*) input;
+ (IMRegistRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRegistRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRegistRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRegistResBuilder : PBGeneratedMessageBuilder {
@private
  IMRegistRes* resultImregistRes;
}

- (IMRegistRes*) defaultInstance;

- (IMRegistResBuilder*) clear;
- (IMRegistResBuilder*) clone;

- (IMRegistRes*) build;
- (IMRegistRes*) buildPartial;

- (IMRegistResBuilder*) mergeFrom:(IMRegistRes*) other;
- (IMRegistResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRegistResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasServerTime;
- (UInt32) serverTime;
- (IMRegistResBuilder*) setServerTime:(UInt32) value;
- (IMRegistResBuilder*) clearServerTime;

- (BOOL) hasResultCode;
- (RegistResult) resultCode;
- (IMRegistResBuilder*) setResultCode:(RegistResult) value;
- (IMRegistResBuilder*) clearResultCode;

- (BOOL) hasResultString;
- (NSString*) resultString;
- (IMRegistResBuilder*) setResultString:(NSString*) value;
- (IMRegistResBuilder*) clearResultString;

- (BOOL) hasUserInfo;
- (UserInfo*) userInfo;
- (IMRegistResBuilder*) setUserInfo:(UserInfo*) value;
- (IMRegistResBuilder*) setUserInfoBuilder:(UserInfoBuilder*) builderForValue;
- (IMRegistResBuilder*) mergeUserInfo:(UserInfo*) value;
- (IMRegistResBuilder*) clearUserInfo;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMRegistResBuilder*) setAttachData:(NSData*) value;
- (IMRegistResBuilder*) clearAttachData;
@end


// @@protoc_insertion_point(global_scope)
